import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/styles/globals.scss";

const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "РИО Мебельный центр",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
